const PROJECTS = [
  {
    id: "1",
    title: "QuickCalc",
    shortDescription:
      "iOS, iPadOS, MacOS app that gathers tools for your daily calcuations",
    shortDescriptionAr:
      "تطبيق iOS ،iPadOS ،MacOS يجمع أدوات بسيطة لحساباتك اليومية",
    githubURL: "https://github.com/BR19-gh/QuickCalc",
    githubImg:
      "https://github-readme-stats.vercel.app/api/pin/?username=BR19-gh&repo=QuickCalc&show_icons=true&theme=transparent&hide_border=true",
    skills: [
      "React Native",
      "Expo",
      "Redux",
      "iOS Development",
      "Nativewind",
      "Javascript",
      "NPM Packages",
    ],
    image: null,
    key: "myTools",
  },
  {
    id: "5",
    title: "br19-portifolio",
    shortDescription: "This portfolio website",
    shortDescriptionAr: "هذا الموقع الشخصي",
    githubURL: "https://github.com/BR19-gh/br19-portifolio",
    githubImg:
      "https://github-readme-stats.vercel.app/api/pin/?username=BR19-gh&repo=br19-portifolio&show_icons=true&theme=transparent&hide_border=true",
    skills: [
      "React Native",
      "TypeScript",
      "Expo",
      "GlueStack-UI",
      "Nativewind",
      "expo-router",
      "npm",
      "netlify",
    ],
    image: null,
    key: "myportfolioNew",
  },
  {
    id: "6",
    title: "Employee Polls",
    shortDescription: "Participate and create polls",
    shortDescriptionAr: "مشاركة وإنشاء استطلاعات",
    githubURL: "https://github.com/BR19-gh/employeePolls-Udacity",
    githubImg:
      "https://github-readme-stats.vercel.app/api/pin/?username=BR19-gh&repo=employeePolls-Udacity&show_icons=true&theme=transparent&hide_border=true",
    skills: [
      "Bootsrap-React",
      "React",
      "Redux",
      "Javascript",
      "CSS",
      "react-router",
      "npm",
    ],
    image: null,
    key: "employeePolls-Udacity",
  },
  {
    id: "2",
    title: "OSBS",
    shortDescription: "Online Store Billing System",
    shortDescriptionAr: "نظام فوترة ومتجر الكتروني",
    githubURL: "https://github.com/BR19-gh/online-store-billing-system",
    githubImg:
      "https://github-readme-stats.vercel.app/api/pin/?username=BR19-gh&repo=online-store-billing-system&show_icons=true&theme=transparent&hide_border=true",
    skills: [
      "Bootsrap",
      "Flask",
      "Python",
      "Javascript",
      "HTML",
      "CSS",
      "SQL",
      "Heroku",
      "PostgresSQL",
    ],
    image: null,
    key: "online-store-billing-system",
  },
  {
    id: "3",
    title: "RSD",
    shortDescription: "Record students degrees management system",
    shortDescriptionAr: "نظام لإدارة درجات الطلاب",
    githubURL: "https://github.com/BR19-gh/rsd",
    githubImg:
      "https://github-readme-stats.vercel.app/api/pin/?username=BR19-gh&repo=rsd&show_icons=true&theme=transparent&hide_border=true",
    skills: [
      "Bootsrap",
      "Flask",
      "Python",
      "Javascript",
      "HTML",
      "CSS",
      "SQL",
      "Heroku",
      "PostgresSQL",
    ],
    image: null,
    key: "rsd",
  },
  {
    id: "4",
    title: "Runman",
    shortDescription: "Side-scrolling pixel game",
    shortDescriptionAr: "لعبة منصات برسوم بكسلية",
    githubURL: "https://github.com/BR19-gh/Runman",
    githubImg:
      "https://github-readme-stats.vercel.app/api/pin/?username=BR19-gh&repo=Runman&show_icons=true&theme=transparent&hide_border=true",
    skills: [
      "Bootsrap",
      "Javascript",
      "HTML",
      "CSS",
      "SQL",
      "Heroku",
      "PostgresSQL",
      "Python",
      "Flask",
    ],
    image: null,
    key: "Runman",
  },
  {
    id: "7",
    title: "Github",
    shortDescription: "Find more in Github",
    shortDescriptionAr: "للمزيد من المشاريع Github زوروا",
    githubURL: "https://github.com/BR19-gh",
    githubImg:
      "https://github-readme-stats.vercel.app/api/pin/?username=BR19-gh&repo=BR19-gh&show_icons=true&theme=transparent&hide_border=true",
    skills: [],
    image: null,
    key: "moreInGithub",
  },
];

export default PROJECTS;
